# Generated by Django 2.1.5 on 2019-04-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='alcohol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='smoke',
            field=models.BooleanField(default=False),
        ),
    ]
